FROM --platform=$BUILDPLATFORM node:20-alpine AS deps
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

FROM --platform=$BUILDPLATFORM deps AS build
WORKDIR /app

COPY . .
RUN npx nx build client

FROM nginx:1.25-alpine

COPY deploy/client.nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/client /usr/share/nginx/html

EXPOSE 3000
