FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app

COPY api-java/pom.xml ./api-java/pom.xml
RUN mvn -f api-java/pom.xml -DskipTests dependency:go-offline

COPY api-java ./api-java
RUN mvn -f api-java/pom.xml clean package -DskipTests

FROM eclipse-temurin:21-jre-jammy AS runtime
WORKDIR /app

ENV SERVER_PORT=3000

COPY --from=build /app/api-java/target/api-java-0.0.1-SNAPSHOT.jar /app/app.jar

EXPOSE 3000

CMD ["java", "-jar", "/app/app.jar"]
