server:
  port: ${SERVER_PORT:3000}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/youwo_homework}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: false
    locations: classpath:db/migration
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: ${GRAPHQL_PATH:/api/graphql}

app:
  graphql:
    path: ${GRAPHQL_PATH:/api/graphql}

logging:
  level:
    root: INFO
